nelmio_api_doc:
    documentation:
            schemes: [http, https]
            info:
                title: Test App
                description: This is an awesome app!
                version: 1.0.0
            securityDefinitions:
                Bearer:
                    type: apiKey
                    description: 'Value: Bearer {jwt}'
                    name: Authorization
                    in: header
#                OAuth2:
#                  type: oauth2
#                  flow: accessCode
#                  authorizationUrl: ^/api/oauth/authorize
#                  tokenUrl: ^/api/token
#                  scopes:
#                    read: Grants read access
#                    write: Grants write access
#                    admin: Grants read and write access to administrative information
            security:
                - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
